name: Java CI

on:
  pull_request:
    branches:
      - next
  push:
    branches:
      - next

jobs:

  package:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 13

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true package

  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 13
        docker-img:
          - docker.io/arangodb/arangodb:3.4.8
          - docker.io/arangodb/enterprise:3.4.8
          - docker.io/arangodb/arangodb:3.5.3
          - docker.io/arangodb/enterprise:3.5.3
          - docker.io/arangodb/arangodb:3.6.0
          - docker.io/arangodb/enterprise:3.6.0
          - docker.io/arangodb/enterprise:3.6.0-ubi

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java-version}}
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn -e --no-transfer-progress test -Dtest.docker.image="${{matrix.docker-img}}" -Darango.license.key="$ARANGO_LICENSE_KEY"
        env:
          ARANGO_LICENSE_KEY: ${{secrets.ARANGO_LICENSE_KEY}}
