name: Java CI

on:
  pull_request:
    branches:
      - next
  push:
    branches:
      - next

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true package

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.4.8
          - docker.io/arangodb/enterprise:3.4.8
          - docker.io/arangodb/arangodb:3.5.3
          - docker.io/arangodb/enterprise:3.5.3
          - docker.io/arangodb/arangodb-preview:3.6.0-rc.1
          - docker.io/arangodb/enterprise-preview:3.6.0-rc.1
          - docker.io/arangodb/enterprise-preview:3.6.0-rc.1-ubi

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn --no-transfer-progress test -Dtest.docker.image="${{matrix.docker-img}}" -Darango.license.key="$ARANGO_LICENSE_KEY"
        env:
          ARANGO_LICENSE_KEY: ${{secrets.ARANGO_LICENSE_KEY}}
